### ISSUE TITLE
Neutralino Binary for OSX Crashes

### ISSUE THREAD

**Issue by rwilsonjr** [neutralinojs/neutralinojs#265]
**Expected Behavior** 
Application should launch.
  
**Actual Behavior**  
Process exits with the following:
`dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__14__fs10filesystem14__current_pathEPNS_10error_codeE
  Referenced from: /Users/roy/Downloads/neutralinojs-v1.3.0/./neutralino-mac (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__14__fs10filesystem14__current_pathEPNS_10error_codeE
  Referenced from: /Users/roy/Downloads/neutralinojs-v1.3.0/./neutralino-mac (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libc++.1.dylib
`

**Steps to Reproduce the Problem**  
 1. Launch neutrolino-mac via command line or via Finder.

**Specifications**  
* NeutralinoJs Version: v1.3.0
* Platform: MacOS Mojave (10.14)

**Comment by shalithasuranga** [comment]
Can you double click and open? this one happened when you build from source?

**Comment by tomjn** [comment]
I can confirm that neutralino segfaults on MacOS

>Can you double click and open? this one happened when you build from source?

That's not how it works on MacOS, you can't double click a binary. A `.app` bundle yes, but not a raw binary like that

**Comment by allankenneth** [comment]
I can confirm that this is still an issue in v1.5.0. Any chance of an update? This is tagged as a question, but it's a total show-stopper for me. I'd love to use Neutralino if this could be fixed.
Thanks!

**Comment by shalithasuranga** [comment]
Hey.. all Please download the latest macOs version. it is already tested with different mac devices. You can simply get the latest CLI and try.

**Comment by abulka** [comment]
I updated to the latest - which gave me`@neutralinojs/neu@3.1.0` and still got the exact same crash.

```
$ cd hello-world2/
$ neu run
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__14__fs10filesystem14__current_pathEPNS_10error_codeE
  Referenced from: /Users/Andy/Devel/grapejs-tests/hello-world2/./hello-world2-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__14__fs10filesystem14__current_pathEPNS_10error_codeE
  Referenced from: /Users/Andy/Devel/grapejs-tests/hello-world2/./hello-world2-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

Application was terminated.
```

This issue should be re-opened. Am on Mojave, same as the original poster.

**Comment by tomjn** [comment]
I just followed the getting started instructions and used the `neu` tool to create an app, and it did not segfault on Big Sur 11.2.3

**Comment by abulka** [comment]
I followed the getting started instructions, and it worked on Catalina 10.15.5.

Looks like Mojave 10.14 (and earlier?) has the problem - unfortunately Mojave is still very popular and what I use on most of my machines.

**Comment by shalithasuranga** [comment]
@abulka  Could you please try v2.1.1 .. I think C++ experimental filesystem module was the issue. You can update neu-cli and use `neu update` to get the latest binaries.

**Comment by abulka** [comment]
I updated 
```
$ npm update -g @neutralinojs/neu
$ neu -V
4.1.0
```

then when I ran 
```
$ neu update

(node:21892) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'binaryName' of undefined
    at Object.module.exports.downloadAndUpdateBinaries (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/modules/downloader.js:61:34)
    at Command.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/commands/update.js:8:29)
    at Command.listener (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/bin/neu.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:21892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kfischer-okarin** [comment]
Similar problem here on Mojave.

Both `neu run` and the built application crash with this message.

```
(node:43527) UnhandledPromiseRejectionWarning: dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /project/bin/neutralino-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /project/bin/neutralino-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 ```
 
 I'm using the most recent version 4.1.0

**Comment by georgechitechi** [comment]
> I updated
> 
> ```
> $ npm update -g @neutralinojs/neu
> $ neu -V
> 4.1.0
> ```
> 
> then when I ran
> 
> ```
> $ neu update
> 
> (node:21892) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'binaryName' of undefined
>     at Object.module.exports.downloadAndUpdateBinaries (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/modules/downloader.js:61:34)
>     at Command.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/commands/update.js:8:29)
>     at Command.listener (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:370:29)
>     at Command.emit (events.js:315:20)
>     at Command.parseArgs (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:892:12)
>     at Command.parse (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:642:21)
>     at Object.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/bin/neu.js:10:9)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> (node:21892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:21892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

I observed that To run neu update you have to be in project root and pass the binary name, eg ```neu update my-app``` where my-app is the binaryName. This command worked on windows

**Comment by abulka** [comment]
Ok so when I ran `neu update` earlier, and got the big error, I was not in a neutralino project directory. When I cd into a project directory, `neu update` works OK. Thanks @georgechitechi but it seems it works either with an app name specified `neu update my-app` or just plain `neu update` - on Mac.

However I still get an error running
```bash
$ ./hello-world2-mac 
2021-06-18 14:03:23,385 ERROR [default] Resource file tree generation error: ./res.neu is missing.
2021-06-18 14:03:23,386 ERROR [default] std::exception
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null
Abort trap: 6
```

and running via 
```bash
$ neu run
(node:41733) UnhandledPromiseRejectionWarning: dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/Andy/Devel/grapejs-tests/electron-alternatives/hello-world2/bin/neutralino-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/Andy/Devel/grapejs-tests/electron-alternatives/hello-world2/bin/neutralino-mac (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib


(node:41733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

And creating a brand new project and `neu run` gives me the same error `UnhandledPromiseRejectionWarning` message as above.

**Comment by shalithasuranga** [comment]
Hey..` TypeError: Cannot read property 'binaryName' of undefined` is  thrown becasue the config file is apparently created with an older version of CLI.  If you add the following part (this will be automatically generated with new CLIs), it will work I think.

```json
    "cli": {
        "binaryName": "<yourProjectName>",
        "resourcesPath": "/resources/",
        "clientLibrary": "/resources/js/neutralino.js"
    }
```

**Comment by abulka** [comment]
Yeah ignore the `Cannot read property 'binaryName'` traceback - that only happened because I was not inside a  neutralino project directory. This problem has got nothing to do with old config files - as my projects are freshly created with the latest version of neutralino and do contain the above fragment in `neutralino.config.json` already - I just checked.

**Comment by gomako** [comment]
I know this is an old issue, but it's still open and as of today I am getting the same issue:

````
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /Users/benharvey/code/pomodoro-app/bin/neutralino-mac_x64 (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /Users/benharvey/code/pomodoro-app/bin/neutralino-mac_x64 (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

neu: INFO neutralino-mac_x64 was stopped with success code 0
````

**Steps to Reproduce the Problem**

1. npm install -g @neutralinojs/neu
2. neu create pomodoro
3. cd pomodoro
4. neu run

Have tried running `neu update` in the project directory and run again but no change.

**Specifications**

````
--- Global ---
neu CLI: v9.3.1

--- Project: pomodoro-app (js.neutralino.sample) ---
Neutralinojs binaries: v4.7.0
Neutralinojs client: v3.6.0
Project version: v1.0.0
````
OSX Version 10.14.6

**Comment by barracuda156** [comment]
Any solution to missing `_aligned_alloc`?

**Comment by AlanSkyNet** [comment]
Still cannot build under mojave (needed for legacy apps)

NewApp ast$ neu run
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/ast/Documents/NewApp/bin/neutralino-mac_x64 (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/ast/Documents/NewApp/bin/neutralino-mac_x64
neu: INFO neutralino-mac_x64 was stopped with success code 0

**Comment by jouni-kantola** [comment]
Is MacOS 12+ required for Neutralino, @shalithasuranga? On Big Sur (11.7.2) the same issue occurs. The reason for asking about MacOS v12+ is because of the log:
> built for Mac OS X 12.0

Repro:
```sh
npx @neutralinojs/neu create bug-repro
cd bug-repro
npx @neutralinojs/neu run
```

Running the app results in:
```
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: [REDACTED]/neutralino-bug-repro/bug-repro/bin/neutralino-mac_x64 (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in [REDACTED]/neutralino-bug-repro/bug-repro/bin/neutralino-mac_x64
neu: INFO neutralino-mac_x64 was stopped with success code 0
```

**Comment by aleph1** [comment]
I am having the same issue with `neu run` crashing, so I decided to try compiling new binaries from source to see if it might resolve the issue. I checked out the 4.11.0 brand and tried compiling binaries on M1 Mac running macOS 11.6.3 but attempting to compile the binaries results in an error (the error is in bold below).

I very much want to use Neutralino as an application wrapper, but there is no real communication about this issue, or a proposed solution/timeline for a fix.

neutralinojs-4.11-2.0 % python3 scripts/bz.py --verbose

  ____        _ _     _ ______     _
 |  _ \      (_) |   | |___  /    (_)
 | |_) |_   _ _| | __| |  / / _ __ _
 |  _ <| | | | | |/ _` | / / | '__| |
 | |_) | |_| | | | (_| |/ /__| |  | |
 |____/ \__,_|_|_|\__,_/_____|_|  |_|

 BuildZri v1.0.0 - A minimal build automation tool for C++

    
Compiling Neutralinojs...
Running command: c++ --std=c++17 -I . -I lib -I lib/asio/include -I lib/infoware/include -I lib/efsw/include -I lib/efsw/src helpers.cpp chrome.cpp resources.cpp extensions_loader.cpp errors.cpp main.cpp settings.cpp auth/permission.cpp auth/authbasic.cpp server/router.cpp server/neuserver.cpp api/app/app.cpp api/filesystem/filesystem.cpp api/storage/storage.cpp api/extensions/extensions.cpp api/window/window.cpp api/os/os.cpp api/events/events.cpp api/computer/computer.cpp api/custom/custom.cpp api/debug/debug.cpp api/clipboard/clipboard.cpp lib/tinyprocess/process.cpp lib/easylogging/easylogging++.cc lib/platformfolders/platform_folders.cpp lib/clip/clip.cpp lib/clip/image.cpp lib/infoware/src/version.cpp lib/infoware/src/gpu/OpenCL.cpp lib/infoware/src/gpu/blank_all.cpp lib/infoware/src/gpu/OpenGL.cpp lib/infoware/src/gpu/d3d.cpp lib/infoware/src/cpu/frequency/frequency_darwin.cpp lib/infoware/src/cpu/frequency/frequency_windows.cpp lib/infoware/src/cpu/frequency/frequency_non_windows_non_darwin.cpp lib/infoware/src/cpu/architecture/architecture_windows.cpp lib/infoware/src/cpu/architecture/architecture_non_windows.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_windows.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_non_windows_non_darwin.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_non_windows_non_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_windows.cpp lib/infoware/src/system/memory/memory_windows.cpp lib/infoware/src/system/memory/memory_non_windows_non_darwin.cpp lib/infoware/src/system/memory/memory_darwin.cpp lib/infoware/src/system/kernel_info/kernel_info_windows.cpp lib/infoware/src/system/kernel_info/kernel_info_non_windows.cpp lib/infoware/src/system/displays/displays_x11.cpp lib/infoware/src/system/displays/displays_darwin.cpp lib/infoware/src/system/displays/displays_default_blank.cpp lib/infoware/src/system/displays/displays_windows.cpp lib/infoware/src/system/OS_info/os_info_non_windows_non_darwin.cpp lib/infoware/src/system/OS_info/os_info_windows.cpp lib/infoware/src/system/OS_info/os_info_darwin.cpp lib/infoware/src/system/amounts/amounts_non_windows.cpp lib/infoware/src/system/amounts/amounts_windows.cpp lib/infoware/src/detail/winstring_windows.cpp lib/infoware/src/detail/winstring_non_windows.cpp lib/infoware/src/detail/sysctl_non_darwin.cpp lib/infoware/src/detail/sysctl_darwin.cpp lib/efsw/src/efsw/Mutex.cpp lib/efsw/src/efsw/FileInfo.cpp lib/efsw/src/efsw/Thread.cpp lib/efsw/src/efsw/Log.cpp lib/efsw/src/efsw/FileWatcherFSEvents.cpp lib/efsw/src/efsw/FileWatcherInotify.cpp lib/efsw/src/efsw/FileWatcherCWrapper.cpp lib/efsw/src/efsw/FileWatcherGeneric.cpp lib/efsw/src/efsw/DirWatcherGeneric.cpp lib/efsw/src/efsw/String.cpp lib/efsw/src/efsw/DirectorySnapshotDiff.cpp lib/efsw/src/efsw/WatcherWin32.cpp lib/efsw/src/efsw/FileWatcherImpl.cpp lib/efsw/src/efsw/System.cpp lib/efsw/src/efsw/WatcherInotify.cpp lib/efsw/src/efsw/DirectorySnapshot.cpp lib/efsw/src/efsw/WatcherGeneric.cpp lib/efsw/src/efsw/FileWatcherKqueue.cpp lib/efsw/src/efsw/FileWatcherWin32.cpp lib/efsw/src/efsw/EfswFileSystem.cpp lib/efsw/src/efsw/WatcherFSEvents.cpp lib/efsw/src/efsw/FileWatcher.cpp lib/efsw/src/efsw/Watcher.cpp lib/efsw/src/efsw/WatcherKqueue.cpp lib/efsw/src/efsw/EfswDebug.cpp lib/tinyprocess/process_unix.cpp lib/clip/clip_osx.mm lib/efsw/src/efsw/platform/posix/ThreadImpl.cpp lib/efsw/src/efsw/platform/posix/SystemImpl.cpp lib/efsw/src/efsw/platform/posix/FileSystemImpl.cpp lib/efsw/src/efsw/platform/posix/MutexImpl.cpp -DNEU_VERSION=\"4.11.0\" -DNEU_COMMIT=\"fatal: not a git repository (or any of the parent directories): .git\" -DELPP_NO_DEFAULT_LOG_FILE=1 -DASIO_STANDALONE -DINFOWARE_VERSION=\"0.6.0\" -DINFOWARE_USE_X11 -DWEBVIEW_COCOA=1 -DTRAY_APPKIT=1 -Wno-deprecated-declarations -framework WebKit -framework Cocoa -Os -o ./bin/neutralino-mac_arm64 -arch arm64 
**/bin/sh: -c: line 0: syntax error near unexpected token `('**
/bin/sh: -c: line 0: `c++ --std=c++17 -I . -I lib -I lib/asio/include -I lib/infoware/include -I lib/efsw/include -I lib/efsw/src helpers.cpp chrome.cpp resources.cpp extensions_loader.cpp errors.cpp main.cpp settings.cpp auth/permission.cpp auth/authbasic.cpp server/router.cpp server/neuserver.cpp api/app/app.cpp api/filesystem/filesystem.cpp api/storage/storage.cpp api/extensions/extensions.cpp api/window/window.cpp api/os/os.cpp api/events/events.cpp api/computer/computer.cpp api/custom/custom.cpp api/debug/debug.cpp api/clipboard/clipboard.cpp lib/tinyprocess/process.cpp lib/easylogging/easylogging++.cc lib/platformfolders/platform_folders.cpp lib/clip/clip.cpp lib/clip/image.cpp lib/infoware/src/version.cpp lib/infoware/src/gpu/OpenCL.cpp lib/infoware/src/gpu/blank_all.cpp lib/infoware/src/gpu/OpenGL.cpp lib/infoware/src/gpu/d3d.cpp lib/infoware/src/cpu/frequency/frequency_darwin.cpp lib/infoware/src/cpu/frequency/frequency_windows.cpp lib/infoware/src/cpu/frequency/frequency_non_windows_non_darwin.cpp lib/infoware/src/cpu/architecture/architecture_windows.cpp lib/infoware/src/cpu/architecture/architecture_non_windows.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_windows.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_non_windows_non_darwin.cpp lib/infoware/src/cpu/quantities_cache/quantities_cache_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_non_windows_non_darwin.cpp lib/infoware/src/cpu/vendor_model_name/vendor_model_name_windows.cpp lib/infoware/src/system/memory/memory_windows.cpp lib/infoware/src/system/memory/memory_non_windows_non_darwin.cpp lib/infoware/src/system/memory/memory_darwin.cpp lib/infoware/src/system/kernel_info/kernel_info_windows.cpp lib/infoware/src/system/kernel_info/kernel_info_non_windows.cpp lib/infoware/src/system/displays/displays_x11.cpp lib/infoware/src/system/displays/displays_darwin.cpp lib/infoware/src/system/displays/displays_default_blank.cpp lib/infoware/src/system/displays/displays_windows.cpp lib/infoware/src/system/OS_info/os_info_non_windows_non_darwin.cpp lib/infoware/src/system/OS_info/os_info_windows.cpp lib/infoware/src/system/OS_info/os_info_darwin.cpp lib/infoware/src/system/amounts/amounts_non_windows.cpp lib/infoware/src/system/amounts/amounts_windows.cpp lib/infoware/src/detail/winstring_windows.cpp lib/infoware/src/detail/winstring_non_windows.cpp lib/infoware/src/detail/sysctl_non_darwin.cpp lib/infoware/src/detail/sysctl_darwin.cpp lib/efsw/src/efsw/Mutex.cpp lib/efsw/src/efsw/FileInfo.cpp lib/efsw/src/efsw/Thread.cpp lib/efsw/src/efsw/Log.cpp lib/efsw/src/efsw/FileWatcherFSEvents.cpp lib/efsw/src/efsw/FileWatcherInotify.cpp lib/efsw/src/efsw/FileWatcherCWrapper.cpp lib/efsw/src/efsw/FileWatcherGeneric.cpp lib/efsw/src/efsw/DirWatcherGeneric.cpp lib/efsw/src/efsw/String.cpp lib/efsw/src/efsw/DirectorySnapshotDiff.cpp lib/efsw/src/efsw/WatcherWin32.cpp lib/efsw/src/efsw/FileWatcherImpl.cpp lib/efsw/src/efsw/System.cpp lib/efsw/src/efsw/WatcherInotify.cpp lib/efsw/src/efsw/DirectorySnapshot.cpp lib/efsw/src/efsw/WatcherGeneric.cpp lib/efsw/src/efsw/FileWatcherKqueue.cpp lib/efsw/src/efsw/FileWatcherWin32.cpp lib/efsw/src/efsw/EfswFileSystem.cpp lib/efsw/src/efsw/WatcherFSEvents.cpp lib/efsw/src/efsw/FileWatcher.cpp lib/efsw/src/efsw/Watcher.cpp lib/efsw/src/efsw/WatcherKqueue.cpp lib/efsw/src/efsw/EfswDebug.cpp lib/tinyprocess/process_unix.cpp lib/clip/clip_osx.mm lib/efsw/src/efsw/platform/posix/ThreadImpl.cpp lib/efsw/src/efsw/platform/posix/SystemImpl.cpp lib/efsw/src/efsw/platform/posix/FileSystemImpl.cpp lib/efsw/src/efsw/platform/posix/MutexImpl.cpp -DNEU_VERSION=\"4.11.0\" -DNEU_COMMIT=\"fatal: not a git repository (or any of the parent directories): .git\" -DELPP_NO_DEFAULT_LOG_FILE=1 -DASIO_STANDALONE -DINFOWARE_VERSION=\"0.6.0\" -DINFOWARE_USE_X11 -DWEBVIEW_COCOA=1 -DTRAY_APPKIT=1 -Wno-deprecated-declarations -framework WebKit -framework Cocoa -Os -o ./bin/neutralino-mac_arm64 -arch arm64 '
ERR: Unable to compile Neutralinojs

**Comment by shalithasuranga** [comment]
Hey @aleph1, seems like you need to clone the repo and compile (not download and compile) since the build script uses some git commands internally. Thanks :tada:

**Comment by aleph1** [comment]
Thanks @shalithasuranga, that worked!

If anyone is looking for macOS 11 compatible binaries I have created a repo here: https://github.com/aleph1/neutralinojs-macos-binaries. I am happy to compile binaries for different releases of neutralinojs if anyone needs them.

**Comment by shalithasuranga** [comment]
Thanks so much @jouni-kantola for checking. I think we can close this issue (and other similar issues) after checking with a 10.x version too.

**Comment by shalithasuranga** [comment]
We can close this issue since there are no new comments (hope it works fine on ealier macOS versions). We can look into this again by creating a new issue if this specific issue occurs to another developer :tada:
